{{- if index .Values.infra "datadog-opw" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-opw
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  sources:
  - repoURL: https://helm.datadoghq.com
    chart: observability-pipelines-worker
    targetRevision: 2.17.0
    helm:
      valueFiles:
      - $values/argocd/infra/values/datadog-opw-values.yaml
  - repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    ref: values
  {{- if index .Values.infra "datadog-opw" "sync" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
