{{- if index .Values.infra "datadog-agent-app" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    path: argocd/infra/manifests/datadog
    repoURL: git@github.com:phantomsloth-io/home-lab.git
    targetRevision: HEAD
  {{- if index .Values.infra "datadog-agent-app" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
