{{- if index .Values.infra "kubeshark" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  project: default
  sources:
  - repoURL: https://helm.kubeshark.co
    chart: kubeshark
    targetRevision: 50.2.0
    helm:
      valueFiles: 
      - $values/argocd/infra/values/kubeshark-values.yaml
  - repoURL: git@github.com:phantomsloth-io/home-lab.git
    ref: values
  {{- if index .Values.infra "kubeshark" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
