{{- if index .Values.infra "metallb" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
  - repoURL: https://metallb.github.io/metallb
    targetRevision: "0.14.9"
    chart: metallb
    helm:
      valueFiles: 
      - $values/argocd/infra/values/metallb-values.yaml
  - repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    ref: values
  {{- if index .Values.infra "metallb" "sync" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
