{{- if index .Values.infra "metallb-config" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  source:
    path: argocd/infra/manifests/metallb/
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
  {{- if index .Values.infra "metallb-config" "sync" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
