{{- if index .Values.infra "middleware-agent" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: middleware-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  project: default
  sources:
  - repoURL: https://helm.middleware.io
    chart: mw-kube-agent
    targetRevision: 0.1.2
    helm:
      valueFiles: 
      - $values/argocd/infra/values/middleware-agent-values.yaml
  - repoURL: git@github.com:phantomsloth-io/home-lab.git
    ref: values
  {{- if index .Values.infra "middleware-agent" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
