{{- if index .Values.infra "newrelic" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic
  namespace: argocd
spec:
  project: default
  destination:
    namespace: newrelic
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://helm-charts.newrelic.com
    chart: nri-bundle
    targetRevision: 5.0.25
    helm:
      releaseName: newrelic-bundle
      values: |
        global:
          cluster: {{ .Values.cluster.name }}
      valueFiles:
      - $values/argocd/infra/values/newrelic-values.yaml
  - repoURL: "git@github.com:phantomsloth-io/home-lab.git"
    ref: values
  {{- if index .Values.infra "newrelic" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
