{{- if index .Values.infra "signoz" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  project: default
  sources:
  - repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.8.0
    helm:
      valueFiles: 
      - $values/argocd/infra/values/signoz-values.yaml
  - repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    ref: values
  {{- if index .Values.infra "signoz" "sync" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
