apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: pi-k3s-cluster
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    kubeStateMetricsCore:
      enabled: true
    apm:
      enabled: true
    npm:
      enabled: true
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: true
    admissionController:
      enabled: true
  override:
    nodeAgent:
      env:
      - name: DD_HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      useConfigMap: true
        customAgentConfig:
          vector:
              logs:
                enabled: true
                url: 'http://10.0.0.209:8282'
              metrics:
                enabled: true
                url: 'http://10.0.0.209:8282'
          
