global:
  additionalLabels:
    sidecar.istio.io/inject: "false"
controller:
  podAnnotations:
    ad.datadoghq.com/argocd-application-controller.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "app_controller_endpoint": "http://%%host%%:8082/metrics"
            }
          ]
        }
      }
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 150m
      memory: 250Mi
repoServer:
  podAnnotations:
    ad.datadoghq.com/argocd-repo-server.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "repo_server_endpoint": "http://%%host%%:8084/metrics"
            }
          ]
        }
      }
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 150Mi
dex:
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
    limits:
      cpu: 10m
      memory: 75Mi
redis:
  resources:
    requests:
      cpu: 15m
      memory: 10Mi
    limits:
      cpu: 20m
      memory: 15Mi
applicationSet:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 15m
      memory: 75Mi
notifications:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 15m
      memory: 75Mi
server:
  podAnnotations:
    ad.datadoghq.com/argocd-server.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "api_server_endpoint": "http://%%host%%:8083/metrics"
            }
          ]
        }
      }  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 150m
      memory: 150Mi
  service:   
    loadBalancerIP: 10.0.0.208
    type: LoadBalancer
