global:
  additionalLabels:
    sidecar.istio.io/inject: "false"
controller:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 120Mi
dex:
  resources:
    requests:
      cpu: 2m
      memory: 30Mi
    limits:
      cpu: 4m
      memory: 40Mi
redis:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 15m
      memory: 12Mi
applicationSet:
  resources:
    requests:
      cpu: 5m
      memory: 40Mi
    limits:
      cpu: 10m
      memory: 50Mi
notifications:
  resources:
    requests:
      cpu: 2m
      memory: 20Mi
    limits:
      cpu: 5m
      memory: 30Mi
server:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 75m
      memory: 75Mi
  service:   
    loadBalancerIP: 10.0.0.208
    type: LoadBalancer
