global:
  additionalLabels:
    sidecar.istio.io/inject: "false"
controller:
  podAnnotations:
    ad.datadoghq.com/argocd-application-controller.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "app_controller_endpoint": "http://%%host%%:8082/metrics"
            }
          ]
        }
      }
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
repoServer:
  podAnnotations:
    ad.datadoghq.com/argocd-repo-server.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "repo_server_endpoint": "http://%%host%%:8084/metrics"
            }
          ]
        }
      }
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 150Mi
dex:
  resources:
    requests:
      cpu: 2m
      memory: 30Mi
    limits:
      cpu: 4m
      memory: 40Mi
redis:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 15m
      memory: 12Mi
applicationSet:
  resources:
    requests:
      cpu: 5m
      memory: 40Mi
    limits:
      cpu: 10m
      memory: 50Mi
notifications:
  resources:
    requests:
      cpu: 2m
      memory: 20Mi
    limits:
      cpu: 5m
      memory: 30Mi
server:
  podAnnotations:
    ad.datadoghq.com/argocd-server.checks: |
      {
        "argocd": {
          "init_config": {},
          "instances": [
            {
              "api_server_endpoint": "http://%%host%%:8083/metrics"
            }
          ]
        }
      }  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 150m
      memory: 150Mi
  service:   
    loadBalancerIP: 10.0.0.208
    type: LoadBalancer
