controller:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
repoServer:
  resources:
    requests:
      cpu: 20m
      memory: 150Mi
dex:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
redis:
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
applicationSet:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
notifications:
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
server:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
  service:   
    loadBalancerIP: 10.0.0.208
    type: LoadBalancer
