targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  kubeStateMetricsCore:
    enabled: true
  liveContainerCollection:
    enabled: true
  orchestratorExplorer:
    enabled: true
  clusterAgent:
    enabled: true
    container_scrubbing:
      enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  networkMonitoring:
    enabled: true
  remoteConfiguration:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  securityAgent:
    runtime:
      enabled: true
    compliance:
      enabled: true
  serviceMonitoring:
    enabled: true
clusterAgent:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 1000Mi
agents:
  podLabels:
    sidecar.istio.io/inject: "false"
  containers:
    agent:
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1000Mi
      env:
        - name: DD_CONTAINER_IMAGE_ENABLED
          value: "true"
        - name: DD_SBOM_ENABLED
          value: "true"
        - name: DD_SBOM_CONTAINER_IMAGE_ENABLED
          value: "true"
        - name: DD_SBOM_HOST_ENABLED
          value: "true"
    processAgent:
      resources: 
        requests:
          cpu: 100m
          memory: 200Mi
    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    systemProbe:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    initContainers:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
  useConfigMap: true
  customAgentConfig:
    vector:
      logs:
        enabled: true
        url: 'http://10.0.0.209:8282'
      metrics:
        enabled: true
        url: 'http://10.0.0.209:8282'
