datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  kubeStateMetricsCore:
    enabled: true
  liveContainerCollection:
    enabled: true
  orchestratorExplorer:
    enabled: true
  clusterAgent:
    enabled: true
    container_scrubbing:
      enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  networkMonitoring:
    enabled: true
  remoteConfiguration:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
clusterAgent:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
agents:
  podLabels:
    sidecar.istio.io/inject: "false"
  containers:
    agent:
      resources:
        requests:
          cpu: 500m
          memory: 256Mi
  useConfigMap: true
  customAgentConfig:
    vector:
      logs:
        enabled: true
        url: 'http://10.0.0.209:8282'
      metrics:
        enabled: true
        url: 'http://10.0.0.209:8282'
