controller:
  resources:
    requests:
      cpu: 5m
      memory: 50Mi
speaker:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 10.0.0.200-10.0.0.250
