deployment:
  labels: []
  annotations: {}
containers:
  labels: []
  annotations: {}
  secrets:
    discordSecret: discord-secret
    nasaSecret: nasa-secret

replicas: 1

image: ghcr.io/phantomsloth-io/discord-bot:main

imagePullSecrets:
  secret: dockerconfigjson-github-com

datadog:
  labels:
    env: Prod
