containers:
  labels: []
  annotations: []
  envFrom:
    secretRef:
      discordSecret: discord-secret
      nasaSecret: nasa-secret

replicas: 1

image: ghcr.io/phantomsloth-io/discord-bot:main

imagePullSecrets:
  secret: discordSecret

datadog:
  labels:
    env: Prod
