apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: {{ .Values.containers.labels | nindent 4 }}
    tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.version }}
  annotations: {{ .Values.containers.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels: {{ .Values.containers.labels | nindent 8 }}
        tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.version }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secret }}
      containers:
      — name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        envFrom:
        - secretRef:
          name: {{ .Values.envFrom.secretRef.discordSecret }}
        - secretRef:
          name: {{ .Values.envFrom.secretRef.nasaSecret }}
            
