apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: 
    {{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4 }}
    {{- end }}
    tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.Version }}
  annotations: 
    {{- if .Values.deployment.annotations }}
{{ tpl (toYaml .Values.deployment.annotations) . | indent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels: 
        {{- if .Values.container.labels }}
{{ toYaml .Values.container.labels | indent 8 }}
        {{- end }}
        tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.Version }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secret }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        envFrom:
        - secretRef:
          name: {{ .Values.containerSecrets.discordSecret }}
        - secretRef:
          name: {{ .Values.containerSecrets.nasaSecret }}
            
