apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: 
{{- range $name, $value := .Values.containers.labels }}
    {{ $name | quote }}: {{ $value | quote }}
{{- end -}}
    tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.Version }}
  annotations: 
    {{ toYaml .Values.containers.annotations | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels: 
{{- range $name, $value := .Values.containers.labels }}
        {{ $name | quote }}: {{ $value | quote }}
{{- end -}}
        tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.Version }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secret }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        envFrom:
        - secretRef:
          name: {{ .Values.containerSecrets.discordSecret }}
        - secretRef:
          name: {{ .Values.containerSecrets.nasaSecret }}
            
