{{- if index .Values.apps "apps" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argocd/apps/
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
  {{- if index .Values.apps "apps" "sync" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
