{{- if index .Values.apps "discord-bot" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  project: default
  sources:
  - repoURL: 'https://github.com/phantomsloth-io/discord-bot.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values/values.yaml
  - repoURL: 'git@github.com:phantomsloth-io/discord-bot.git'
    ref: values
  {{- if index .Values.apps "discord-bot" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
