{{- if index .Values.apps "discord-bot" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord-bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: discord-bot
  project: default
  sources:
  - repoURL: 'https://phantomsloth-io.github.io/helm'
    targetRevision: 1.0.10
    chart: discord-bot
    helm:
      valueFiles:
        - $values/argocd/apps/values/discord-bot-values.yaml
  - repoURL: 'git@github.com:phantomsloth-io/home-lab.git'
    ref: values
  {{- if index .Values.apps "discord-bot" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
