{{- if index .Values.infra "plex" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
  - repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: "0.1.5"
    chart: plex-media-server
    helm:
      valueFiles: 
      - $values/argocd/infra/values/plex-values.yaml
  - repoURL: git@github.com:phantomsloth-io/home-lab.git
    ref: values
  {{- if index .Values.infra "plex" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
