global:
  repoURL: https://github.com/phantomsloth-io/home-lab.git
  targetRevision: HEAD

cluster:
  name: "pi-k3s-cluster"
  project: default

infra:
  infra:
    enabled: true
    sync: true
  namespaces:
    enabled: true
    sync: true
  argocd:
    enabled: true
    sync: true
  metallb:
    enabled: true
    sync: true
  metallb-config:
    enabled: true
    sync: true
  datadog-opw:
    enabled: false
    sync: false
