name: build-deploy-discord-bot
run-name: Discord bot GHA
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Determine project name
      #   run: echo "PROJECT_NAME=$(git remote get-url origin | rev | cut -f 1 -d / | cut -f 2 -d . | rev)" >> ${GITHUB_ENV}
      - name: Determine project version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> ${GITHUB_ENV}
      # - name: Install Task
      #   uses: arduino/setup-task@v1
      # - name: Install Golang
      #   uses: actions/setup-go@v3
      # - name: Establish AWS session
      #   uses: aws-actions/configure-aws-credentials@v2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        uses: docker/build-push-action@v4.2.1
        with:
          # Path to the Dockerfile
          file: apps/discord-bot/dockerfile
          # List of target platforms for build
          platforms: # optional
          # List of tags
          tags: # optional
          # GitHub Token used to authenticate against a repository for Git context
          github-token: ${{ github.token }}
