apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
spec:
  destination:
    namespace: datadog
    server: https://kubernetes.default.svc
  project: default
  source:
    - chart: datadog-operator
      repoURL: https://helm.datadoghq.com
      targetRevision: 1.1.0
      helm:
        releaseName: datadog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
