apiVersion: argoproj.io/v1alpha1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog
spec:
  project: default
  interval: 5m
  chart:
    spec:
      chart: datadog-operator
      version: 1.1.0
      sourceRef:
      kind: HelmRepository
      name: datadog-operator
      namespace: datadog
