{{- if index .Values.infra "argocd" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.43.3
    helm:
      valueFiles: 
      - $values/infra/values/argocd-values.yaml
  - repoURL: git@github.com:phantomsloth-io/home-lab.git
    ref: values
  {{- if index .Values.infra "argocd" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
