apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-opw
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    chart: observability-pipelines-worker
    repoURL: https://helm.datadoghq.com
    targetRevision: 1.3.1
