{{- if index .Values.infra "datadog-agent" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc  
    namespace: datadog
  sources:
  - repoURL: https://helm.datadoghq.com
    targetRevision: 3.34.0
    chart: datadog
    helm:
      values: |
            datadog:
              clusterName: {{ .Values.cluster.name }}
      valueFiles:
        - $values/infra/values/datadog-agent-values.yaml
  - repoURL: "git@github.com:phantomsloth-io/home-lab.git"
    ref: values
  {{- if index .Values.infra "datadog-agent" "sync" }}
  syncPolicy:
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        istio-injection: enabled
    syncOptions:
    - CreateNamespace=true
    automated: {}
  {{- end }}
{{- end }}
