apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-operator
  namespace: argocd
destination:
  server: https://kubernetes.default.svc  
  namespace: datadog
spec:
  project: default
  sources:
  - repoURL: https://helm.datadoghq.com
    targetRevision: 1.1.0
    chart: datadog-operator
    helm:
      valueFiles:
      - $values/infra/values/datadog-operatior-values.yaml
  - repoURL: "git@github.com:Two-watch-boy/home-lab.git"
    ref: values
  
