apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  project: default
  source:
    path: infra/manifests/datadog
    repoURL: git@github.com:Two-watch-boy/home-lab.git
    targetRevision: HEAD
