{{- if index .Values.apps "metallb" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  sources:
  - repoURL: https://metallb.github.io/metallb
    targetRevision: "0.13.10"
    chart: metallb
    helm:
      valueFiles: 
      - $values/infra/values/metallb-values.yaml
  - repoURL: git@github.com:Two-watch-boy/home-lab.git
    ref: values
  {{- if index .Values.apps "metallb" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
