{{- if index .Values.apps "namespaces" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/manifests/namespaces
    repoURL: git@github.com:Two-watch-boy/home-lab.git
    targetRevision: HEAD
  {{- if index .Values.apps "namespaces" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
