{{- if index .Values.apps "root" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: infra/
    repoURL: git@github.com:phantomsloth-io/home-lab.git
    targetRevision: HEAD
  {{- if index .Values.apps "root" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
