{{- if index .Values.apps "vector-agent" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vector
  project: default
  sources:
  - repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.24.0
    helm:
      valueFiles: 
      - $values/infra/values/vector-values.yaml
  - repoURL: git@github.com:Two-watch-boy/home-lab.git
    ref: values
  {{- if index .Values.apps "vector-agent" "sync" }}
  syncPolicy:
    automated: {}
  {{- end }}
{{- end }}
